blank_issues_enabled: false
contact_links:
  - name: âš  Feature request
    url: https://github.com/Tyrrrz/.github/blob/master/docs/project-status.md
    about: Sorry, but this project is in maintenance mode and no longer accepts new feature requests.
  - name: ðŸ“– Documentation
    url: https://github.com/Tyrrrz/YoutubeDownloader/wiki
    about: Find usage guides and frequently asked questions.
  - name: ðŸ—¨ Discussions
    url: https://github.com/Tyrrrz/YoutubeDownloader/discussions/new
    about: Ask and answer questions.
  - name: ðŸ’¬ Discord server
    url: https://discord.gg/2SUWKFnHSm
    about: Chat with the project community.
